use vtable_rs::VPtr;

#[vtable_rs::vtable]
pub trait CSMsgRepositoryVmt {
    extern "C" fn destructor(&mut self, param_2: u32);
}

impl CSMsgRepositoryVmt for CSMsgRepositoryImp {
    extern "C" fn destructor(&mut self, param_2: u32) {
        // Add the implementation logic here
        println!("Destructor called with param_2: {}", param_2);
    }
}

impl Default for CSMsgRepositoryImp {
    fn default() -> Self {
        Self {
            vftable: VPtr::new(),
            cs_res_manager: *b"CSResManager",
            _pad0: [0; 2],
            talk_msg: *b"? T a l k M s g ?\0",
            _pad1: [0; 6],
            blood_msg: *b"? B l o o d M s g ?\0",
            _pad2: [0; 4],
            goods_name: *b"? G o o d s N a m e ?\0",
            _pad3: [0; 2],
            goods_info: *b"? G o o d s I n f o ?\0",
            _pad4: [0; 2],
            goods_caption: *b"? G o o d s C a p t i o n ?\0",
            _pad5: [0; 4],
            goods_dialog: *b"? G o o d s D i a l o g ?\0",
            _pad6: [0; 6],
            weapon_name: *b"? W e a p o n N a m e ?\0",
            _pad7: [0; 8],
            weapon_info: *b"? W e a p o n I n f o ?\0",
            _pad8: [0; 8],
            weapon_caption: *b"? W e a p o n C a p t i o n ?\0",
            _pad9: [0; 2],
            protector_name: *b"? P r o t e c t o r N a m e ?\0",
            _pad10: [0; 2],
            protector_info: *b"? P r o t e c t o r I n f o ?\0",
            _pad11: [0; 2],
            protector_caption: *b"? P r o t e c t o r C a p t i o n ?\0",
            _pad12: [0; 4],
            accessory_name: *b"? A c c e s s o r y N a m e ?\0",
            _pad13: [0; 2],
            accessory_info: *b"? A c c e s s o r y I n f o ?\0",
            _pad14: [0; 2],
            accessory_caption: *b"? A c c e s s o r y C a p t i o n ?\0",
            _pad15: [0; 4],
            magic_name: *b"? M a g i c N a m e ?\0",
            _pad16: [0; 2],
            arts_name: *b"? A r t s N a m e ?\0",
            _pad17: [0; 4],
            arts_caption: *b"? A r t s C a p t i o n ?\0",
            _pad18: [0; 6],
            network_message: *b"? N e t w o r k M e s s a g e ?\0",
            _pad19: [0; 8],
            action_button_text: *b"? A c t i o n B u t t o n T e x t ?\0",
            _pad20: [0; 4],
            event_text_for_talk: *b"? E v e n t T e x t F o r T a l k ?\0",
            _pad21: [0; 4],
            event_text_for_map: *b"? E v e n t T e x t F o r M a p ?\0",
            _pad22: [0; 6],
            dialog: *b"? D i a l o g ?\0",
            _pad23: [0; 8],
            menu_common: *b"? M e n u C o m m o n ?\0",
            _pad24: [0; 8],
            test_error: *b"? T e s t E r r o r ?\0",
            _pad25: [0; 8],
            tag_error: *b"? T a g E r r o r ?\0",
            _pad26: [0; 2],
            sysmsg: *b"? S y s m s g ?\0",
            _pad27: [0; 8],
            npc_name: *b"? N p c N a m e ?\0",
            _pad28: [0; 6],
            place_name: *b"? P l a c e N a m e ?\0",
            _pad29: [0; 2],
            menu_text: *b"? M e n u T e x t ?\0",
            _pad30: [0; 4],
            sell_region: *b"? S e l l R e g i o n ?\0",
            _pad31: [0; 8],
            msg_tag_man1: *b"MsgTagMan\0",
            _pad32: [0; 6],
            msg_tag_man2: *b"M s g T a g M a n\0",
            _pad33: [0; 6],
        }
    }
}

#[repr(C)]
pub struct CSMsgRepositoryImp {
    vftable: VPtr<dyn CSMsgRepositoryVmt, Self>,
    cs_res_manager: [u8; 12],
    _pad0: [u8; 2],
    talk_msg: [u8; 18],
    _pad1: [u8; 6],
    blood_msg: [u8; 20],
    _pad2: [u8; 4],
    goods_name: [u8; 22],
    _pad3: [u8; 2],
    goods_info: [u8; 22],
    _pad4: [u8; 2],
    goods_caption: [u8; 28],
    _pad5: [u8; 4],
    goods_dialog: [u8; 26],
    _pad6: [u8; 6],
    weapon_name: [u8; 24],
    _pad7: [u8; 8],
    weapon_info: [u8; 24],
    _pad8: [u8; 8],
    weapon_caption: [u8; 30],
    _pad9: [u8; 2],
    protector_name: [u8; 30],
    _pad10: [u8; 2],
    protector_info: [u8; 30],
    _pad11: [u8; 2],
    protector_caption: [u8; 36],
    _pad12: [u8; 4],
    accessory_name: [u8; 30],
    _pad13: [u8; 2],
    accessory_info: [u8; 30],
    _pad14: [u8; 2],
    accessory_caption: [u8; 36],
    _pad15: [u8; 4],
    magic_name: [u8; 22],
    _pad16: [u8; 2],
    arts_name: [u8; 20],
    _pad17: [u8; 4],
    arts_caption: [u8; 26],
    _pad18: [u8; 6],
    network_message: [u8; 32],
    _pad19: [u8; 8],
    action_button_text: [u8; 36],
    _pad20: [u8; 4],
    event_text_for_talk: [u8; 36],
    _pad21: [u8; 4],
    event_text_for_map: [u8; 34],
    _pad22: [u8; 6],
    dialog: [u8; 16],
    _pad23: [u8; 8],
    menu_common: [u8; 24],
    _pad24: [u8; 8],
    test_error: [u8; 22],
    _pad25: [u8; 8],
    tag_error: [u8; 20],
    _pad26: [u8; 2],
    sysmsg: [u8; 16],
    _pad27: [u8; 8],
    npc_name: [u8; 18],
    _pad28: [u8; 6],
    place_name: [u8; 22],
    _pad29: [u8; 2],
    menu_text: [u8; 20],
    _pad30: [u8; 4],
    sell_region: [u8; 24],
    _pad31: [u8; 8],
    msg_tag_man1: [u8; 10],
    _pad32: [u8; 6],
    msg_tag_man2: [u8; 18],
    _pad33: [u8; 6],
}
